### ISSUE TITLE
total joint error

### ISSUE THREAD

**Issue by louisgag** [gdbaldw/BlenderAndMBDyn#19]
Dear Doug,
Sorry for bothering you again, but I've found that if I don't assign a drive to each of the 6 DoFs of a total joint (in displacement in this case) BAMv2 gives me an error. It would seem counterintuitive with the checkbox option which hints that it is optional to specify a drive for each DoF.
Best Regards,
-Louis

**Comment by gdbaldw** [comment]
Dear Louis,
Thanks for reporting this bug. Please confirm that the latest update works as expected for you.
Cheers,
-Doug

**Comment by louisgag** [comment]
I've just tested it and the issue is fixed.
Thank you!
