### ISSUE TITLE
Installing Blender from blender.org

### ISSUE THREAD

**Issue by gdbaldw** [gdbaldw/BlenderAndMBDyn#22]
Unfortunately, pre-compiled Blender from blender.org expects all Python libraries to reside in its local directory, and is unable to import Pandas for plotting. While there may be a way to link and properly access the system libraries needed for Pandas, or to install Pandas in the local blender file system, no working recipe has been found to date.

Fortunately, for Ubuntu users, Thomas Schiex's personal Ubuntu repository contains the latest Blender version.

A recipe that does work is:

1) Uninstall Blender from the Ubuntu Software Center.

2) From a commandline, add the personal repository and update apt:

sudo add-apt-repository ppa:thomas-schiex/blender
sudo apt-get update

3) Install Blender as usual from the Ubuntu Software Center.

Now, the latest Blender is installed, and if Pandas for Python3 is installed, plotting should also work within Blender. (Pandas for Python2.7 is no longer required.)

-Doug

**Comment by louisgag** [comment]
Dear Doug,
thanks for pointing out this solution. Would compiling Blender myself also work as a possible solution ?
Regards,
-Louis

**Comment by gdbaldw** [comment]
Dear Louis,
Yes, with two caveats: 1) a simpler solution with the pre-compiled versions from blender.org could possibly be found, which might be preferable, and 2) I've personally never had a need to nor have I compiled Blender, so have no further advice on this approach.
Regards,
-Doug

**Comment by louisgag** [comment]
Dear Doug,
Unfortunately the blender version I got from the repository does not load. I'll attempt to compile it myself.
Regards,
-Louis

**Comment by louisgag** [comment]
Hello again Doug,
I tried quickly to compile Blender with my python lib and gave up. I also looked at the possibility to install pandas into the Blender distributed python lib with no success. I however think that if the users need to compile their blender version to use BAMv2 it will be a major dissuasion. Plotting is not the most important aspect of the plugin, but it still is a very useful option..
Have nice week-end!
-Louis

**Comment by gdbaldw** [comment]
This issue will resolve itself, since Blender v2.72 is the minimum required version. Debian stable already supports v2.72, and Ubuntu 14.04 has the v2.76 solution outlined above.

**Comment by Moke2015** [comment]
All,

I tried to commit to changes to github today. I didn't succeed yet. I 
keep trying.

Secondly, I did resolve the issue with missing sub menus. In case this 
comes up again for BAM2:

Hardware was: ATI Radeon HD 2600
Operating system: Ubuntu 14.04.3 64 bit

I had to change the Blender user preferences->system->Window draw 
method->switched to triple buffer

Now the menus appear and I have not encountered further issues.

Best Regards,

Morten

**Comment by Moke2015** [comment]
All,

I tried to submit the changes to Github today. I didn't succeed yet.

In addition, I did overcome my issue with missing sub menus. I simply 
had to change
the blender user preferences->system->window draw method->switched to 
triple buffer.

This change finally allows me to work under linux now.

Best Regards,

Morten

**Comment by Moke2015** [comment]
All,

I did try to submit the changes to Github today. I did not succeed yet. 
I keep trying.

By the way, I did overcome the issue with missing sub menus on my linux 
system. I had
to change the blender user preferences ->system->Window draw method-> 
switched to
triple buffer. This fixed the issue.

Best Regards,

Morten

**Comment by louisgag** [comment]
Dear Morten,
you have to "git push" the changes to your forked BAMv2: 
https://help.github.com/articles/pushing-to-a-remote/
Also make sure you "git add" the files you created, if any.
Regards,
-Louis

On 08-Nov-2015 05:40 PM, Moke2015 wrote:

> All,
> 
> I did try to submit the changes to Github today. I did not succeed yet.
> I keep trying.
> 
> By the way, I did overcome the issue with missing sub menus on my linux
> system. I had
> to change the blender user preferences ->system->Window draw method->
> switched to
> triple buffer. This fixed the issue.
> 
> Best Regards,
> 
> Morten
> 
> On 06.11.2015 15:59, gdbaldw wrote:
> 
> > This issue will resolve itself, since Blender v2.72 is the minimum
> > required version. Debian stable already supports v2.72, and Ubuntu
> > 11.04 has the v2.76 solution outlined above.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-154430876.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-154840032.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by Moke2015** [comment]
Thanks Louis,
 
I will try tonight.
 
Best Regards,
 
Morten 
-----Ursprüngliche Nachricht-----
 Von: "louisgag" [notifications@github.com]
 Gesendet: Mo. 09.11.2015 09:39
 An: "gdbaldw/BlenderAndMBDyn" [BlenderAndMBDyn@noreply.github.com]
 Kopie: "Moke2015" [Morten.Ketelsen@freenet.de]
 Betreff: Re: [BlenderAndMBDyn] Installing Blender from blender.org (#22)

Dear Morten,
 you have to "git push" the changes to your forked BAMv2: 
 https://help.github.com/articles/pushing-to-a-remote/
 Also make sure you "git add" the files you  already supports v2.72, and Ubuntu

> > 11.04 has the v2.76 solution outlined above.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> .

 -- 
 Louis Gagnon, Ph.D.
 Dipartimento di Scienze e Tecnologie Aerospaziali
 Politecnico di Milano

—
Reply to this email directly or view it on GitHub.
-----Ursprüngliche Nachricht Ende-----

---

Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen! Rundum glücklich mit freenetMail

**Comment by louisgag** [comment]
No problem. On a different note, where you able to make the plotting work ?
-Louis

On 09-Nov-2015 12:27 PM, Moke2015 wrote:

> Thanks Louis,
> 
> I will try tonight.
> 
> Best Regards,
> 
> Morten
> -----Ursprüngliche Nachricht-----
> Von: "louisgag" [notifications@github.com]
> Gesendet: Mo. 09.11.2015 09:39
> An: "gdbaldw/BlenderAndMBDyn" [BlenderAndMBDyn@noreply.github.com]
> Kopie: "Moke2015" [Morten.Ketelsen@freenet.de]
> Betreff: Re: [BlenderAndMBDyn] Installing Blender from blender.org (#22)
> 
> Dear Morten,
> you have to "git push" the changes to your forked BAMv2:
> https://help.github.com/articles/pushing-to-a-remote/
> Also make sure you "git add" the files you already supports v2.72, and 
> Ubuntu
> 
> > > 11.04 has the v2.76 solution outlined above.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > .
> 
> ## 
> 
> Louis Gagnon, Ph.D.
> Dipartimento di Scienze e Tecnologie Aerospaziali
> Politecnico di Milano
> 
> —
> Reply to this email directly or view it on GitHub.
> -----Ursprüngliche Nachricht Ende-----
> 
> ---
> 
> Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse 
> mitnehmen! Rundum glücklich mit freenetMail
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-155033590.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by Moke2015** [comment]
I will be working on plotting later, once I have overcome my issues with 
github.

Best Regards,

Morten

**Comment by Moke2015** [comment]
All,

I am close to give up. I keep wasting my time with github.

This is what I did:
- I forked Dougs repository on github
- I cloned my fork to my local drive

git init

git clone https://github.com/Moke2015/BlenderAndMBDyn.git
git add element.py
git add menu.py
git add simulator.py

git commit -m "Addition of total pin joint with partial coverage of 
input options"

[master (root-commit) 657ca36] Addition of total pin joint with partial 
coverage of input options
  3 files changed, 2406 insertions(+)
  create mode 100644 element.py
  create mode 100644 menu.py
  create mode 100644 simulator.py

so far so good, then:

git push https://github.com/Moke2015/BlenderAndMBDyn.git master
To https://github.com/Moke2015/BlenderAndMBDyn.git
  ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 
'https://github.com/Moke2015/BlenderAndMBDyn.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

If I use --force I can get the files to github. But I can not create a 
pull request, since the repositories
seem to posses now an 'entirely different commit history'. Does anybody 
have an idea of what I am
doing wrong?

Best Regards,

Morten

**Comment by Moke2015** [comment]
Hello Louis,

I tried plotting once more. If I start python3 in an terminal, I 
definitely can import pandas.
Nevertheless, in Blender the complaint about the missing hashtable, 
tslib, lib
still appears. The python path also includes the right path. I did check 
on this.

I am using Blender 2.76 on ubuntu 14.04.3.

Regards,

Morten

**Comment by louisgag** [comment]
Dear Morten,
Yes, git can be complicated when you're not used to it. I suffered too...
If we take for granted that your fork is in sync with upstream (Doug's), 
that would be the procedure:

git checkout master git merge upstream/master

|git push origin master

Don't give up and let me know, you may need to redo the whole procedure 
from the start and then copy over the files you modified up to date. 
Thus first by recreating the fork... Why not for the whole repository 
from Doug ?

then you would do:

|
|

cd ~/.config/blender/2.76/scripts/addons/

git clone https://github.com/Moke2015/BlenderAndMBDyn

cd ~/.config/blender/2.76/scripts/addons/BlenderAndMBDyn/
git remote add upstream https://github.com/gdbaldw/BlenderAndMBDyn
git fetch upstream
git checkout master
git merge upstream/master
MAKE YOUR CHANGES TO YOUR LOCAL FILES HERE
git commit FILENAME
|git push origin master Hope this works for you Regards,|

|
|
|

On 09-Nov-2015 08:11 PM, Moke2015 wrote:

> All,
> 
> I am close to give up. I keep wasting my time with github.
> 
> This is what I did:
> - I forked Dougs repository on github
> - I cloned my fork to my local drive
> 
> git init
> 
> git clone https://github.com/Moke2015/BlenderAndMBDyn.git
> git add element.py
> git add menu.py
> git add simulator.py
> 
> git commit -m "Addition of total pin joint with partial coverage of
> input options"
> 
> [master (root-commit) 657ca36] Addition of total pin joint with partial
> coverage of input options
> 3 files changed, 2406 insertions(+)
> create mode 100644 element.py
> create mode 100644 menu.py
> create mode 100644 simulator.py
> 
> so far so good, then:
> 
> git push https://github.com/Moke2015/BlenderAndMBDyn.git master
> To https://github.com/Moke2015/BlenderAndMBDyn.git
> ! [rejected] master -> master (fetch first)
> error: failed to push some refs to
> 'https://github.com/Moke2015/BlenderAndMBDyn.git'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository 
> pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> 
> If I use --force I can get the files to github. But I can not create a
> pull request, since the repositories
> seem to posses now an 'entirely different commit history'. Does anybody
> have an idea of what I am
> doing wrong?
> 
> Best Regards,
> 
> Morten
> 
> On 09.11.2015 12:29, louisgag wrote:
> 
> > No problem. On a different note, where you able to make the plotting
> > work ?
> > -Louis
> > 
> > On 09-Nov-2015 12:27 PM, Moke2015 wrote:git init
> > 
> > > Thanks Louis,
> > > 
> > > I will try tonight.
> > > 
> > > Best Regards,
> > > 
> > > Morten
> > > -----Ursprüngliche Nachricht-----
> > > Von: "louisgag" [notifications@github.com]
> > > Gesendet: Mo. 09.11.2015 09:39
> > > An: "gdbaldw/BlenderAndMBDyn" [BlenderAndMBDyn@noreply.github.com]
> > > Kopie: "Moke2015" [Morten.Ketelsen@freenet.de]
> > > Betreff: Re: [BlenderAndMBDyn] Installing Blender from blender.org 
> > > (#22)
> > > 
> > > Dear Morten,
> > > you have to "git push" the changes to your forked BAMv2:
> > > https://help.github.com/articles/pushing-to-a-remote/
> > > Also make sure you "git add" the files you already supports v2.72, and
> > > Ubuntu
> > > 
> > > > > 11.04 has the v2.76 solution outlined above.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > .
> > > 
> > > ## 
> > > 
> > > Louis Gagnon, Ph.D.
> > > Dipartimento di Scienze e Tecnologie Aerospaziali
> > > Politecnico di Milano
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > -----Ursprüngliche Nachricht Ende-----
> > > 
> > > ---
> > > 
> > > Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse
> > > mitnehmen! Rundum glücklich mit freenetMail
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-155033590.
> > 
> > 
> > ## 
> > 
> > Louis Gagnon, Ph.D.
> > Dipartimento di Scienze e Tecnologie Aerospaziali
> > Politecnico di Milano
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-155034208.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/22#issuecomment-155158928.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by gdbaldw** [comment]
My Ubuntu 14.04 64-bit using the above procedure has Blender 2.76b installed, and through the Software Center also has python3-pandas and python3-pandas-lib installed. This is an unmodified configuration, as provided by Ubuntu, and both plotting and menus work. Inside of Blender, in the scripting console, typing "import sys" followed by "sys.path" confirms that the Python path within Blender reaches the system libraries where Pandas is installed. I also have a Debian stable which has Blender 2.72 and Pandas as installation  packages, and that all works as configured by Debian. This all works as packaged by the software distributors.

-Doug

**Comment by Moke2015** [comment]
Louis,

thanks a lot for your support. I believe, this did work now.

Doug,

can you please check on my pull request?

As you will see rather quickly, the input manual allows also for 
optional relative and absolute
orientations. This is not yet fully implemented. I kept it very simple 
for the beginning and
can extend it.

Please check, if what I have been doing is heading in the right direction.

Best Regards,

Morten

**Comment by gdbaldw** [comment]
Morten,

I see your code in your account, but not as a pull request to my account. The code looks like a great start. I believe mirroring the Total Joint code will work for now.

Best Regards,
Doug

**Comment by Moke2015** [comment]
Hello Doug,

I did another pull request tonight. Please check.

With regard to Pandas, I tried once more. In the python console window, 
the directory for
pandas appears. Nevertheless, the same messages, as reported by Louis 
appear.

cannot import name 'hashtable'

....

Best Regards,

Morten

**Comment by louisgag** [comment]
Dear Doug,
I've tried again to get plotting to work, but without any success. I tried to install the "Thomas" repository Blender and it doesn't work.
I tried this solution: http://stackoverflow.com/questions/33188128/blender-import-pandas-importerror-no-module-named-pandas by linking my python instead of the Blender packaged one, I also tried copying it in the blender/2.76 folders in different ways. I tried to "merge" the two python distribution but nothing gets plotting working. The closest I got to the solution was the "cannot import name 'hashtable'" error message. Finally, I've also noticed that when I link my own python, blender would sometimes not load by giving an error about a package that is not available while when loading it through python I would not get that error.
Hope that a working solution can eventually come up because plotting was a very nice additional feature.
Best Regards,
-Louis

**Comment by louisgag** [comment]
Just to clarify, after importing pandas with my "linked/copied" python, the error I get, which I also get when running directly on my python3 outside of Blender is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/louis/bin/blender-2.76b-linux-glibc211-i686/2.76/python/lib/python3.4/pandas/**init**.py", line 6, in <module>
    from . import hashtable, tslib, lib
ImportError: cannot import name 'hashtable'
