### ISSUE TITLE
Can't add gravity

### ISSUE THREAD

**Issue by apalazzi** [gdbaldw/BlenderAndMBDyn#26]
Hi,

I'm trying to use this plugin to run MBDyn but the tutorial seems to be running a different version of the plugin and I can't figure out how to set the gravity vector.

In the tutorial https://www.youtube.com/watch?v=RKprhyOqHZM a nice windows asking for a vector shows up when Gravity is added, however all I can do is add an array of 3D drives or a template 3D drive.

Whatever I choose, I can't figure out how to add the gravitiy to the problem, can you help me?

I'm using blender 2.77, same thing with blender 2.79.

**Comment by gdbaldw** [comment]
1) Inside Gravity select "New" Template Drive
2) Click Use Drive 3 (the global Z-direction), and select "New" Drive.
3) Make a Constant Drive with value of -9.8
4) OK to save Constant Drive, OK to save Template Drive, OK to save Gravity.

This follows how MBDyn specifies gravity: a 3D field aligned with the global reference frame.
(In the tutorials, and earlier versions, gravity was more intuitive, but did not support the more general cases supported by MBDyn.)


 

 

-----Original Message-----

**Comment by apalazzi** [comment]
Checked and it works, thanks.
