### ISSUE TITLE
Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn'

### ISSUE THREAD

**Issue by timgow** [gdbaldw/BlenderAndMBDyn#5]
Hi,
I have Blender 2.69 and MBDyn 1.6.1 installed on Ubuntu 14.04 LTS.  I would like to use the github.com/gdbaldw/BlenderAndMBDyn addon for Blender.  The addon goes ahead within Blender but I don't get the 'Actions' tab to select 'MBDyn file', 'Run MBDyn' etc..
Please give any suggestions.
![blendermbdyn-gdbaldw_installvideo](https://cloud.githubusercontent.com/assets/14345444/9958432/b749b35a-5e01-11e5-8339-7f9c2ee6057e.JPG)
![blendermbdyn-ubuntu1404lts](https://cloud.githubusercontent.com/assets/14345444/9958433/b74e6058-5e01-11e5-9339-f1ad6fb0bbd3.JPG)
Tim

**Comment by louisgag** [comment]
Hi Tim,

Thanks for your question.
Unfortunately the addon is not very stable with Blender 2.69. The tabs 
don't show clearly and the pop-ups are delayed.
I strongly recommend you download the latest Blender version from the 
official website, on Ubuntu that download is ready to run out of the box 
without even compiling.

Have a nice week-end,

-Louis

On 18-Sep-2015 01:35 PM, timgow wrote:

> Hi,
> I have Blender 2.69 and MBDyn 1.6.1 installed on Ubuntu 14.04 LTS. I 
> would like to use the github.com/gdbaldw/BlenderAndMBDyn addon for 
> Blender. The addon goes ahead within Blender but I don't get the 
> 'Actions' tab to select 'MBDyn file', 'Run MBDyn' etc..
> Please give any suggestions.
> blendermbdyn-gdbaldw_installvideo 
> https://cloud.githubusercontent.com/assets/14345444/9958432/b749b35a-5e01-11e5-8339-7f9c2ee6057e.JPG
> blendermbdyn-ubuntu1404lts 
> https://cloud.githubusercontent.com/assets/14345444/9958433/b74e6058-5e01-11e5-9339-f1ad6fb0bbd3.JPG
> Tim
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/5.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by timgow** [comment]
Hi Louis,
Thank you for your quick reply, much appreciated.
I'm looking forward to using MBDyn within Blender, this is a fantastic project.
Enjoy your weekend too
Tim

p.s. Do you have any experience using FEA flexible elements with MBDyn and Blender?

---

On Fri, 18/9/15, louisgag notifications@github.com wrote:

 Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn' (#5)
 To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Friday, 18 September, 2015, 12:49

 Hi Tim,

 Thanks for your question.

 Unfortunately the addon is not very stable with Blender
 2.69. The tabs 

 don't show clearly and the pop-ups are delayed.

 I strongly recommend you download the latest Blender version
 from the 

 official website, on Ubuntu that download is ready to run
 out of the box 

 without even compiling.

 Have a nice week-end,

 -Louis

 On 18-Sep-2015 01:35 PM, timgow wrote:

> Hi,
> 
> I have Blender 2.69 and MBDyn 1.6.1 installed on Ubuntu
>  14.04 LTS. I 
> 
> would like to use the
>  github.com/gdbaldw/BlenderAndMBDyn addon for 
> 
> Blender. The addon goes ahead within Blender but I
>  don't get the 
> 
> 'Actions' tab to select 'MBDyn file',
>  'Run MBDyn' etc..
> 
> Please give any suggestions.
> 
> blendermbdyn-gdbaldw_installvideo 
> 
>  https://cloud.githubusercontent.com/assets/14345444/9958432/b749b35a-5e01-11e5-8339-7f9c2ee6057e.JPG
> 
> blendermbdyn-ubuntu1404lts 
> 
>  https://cloud.githubusercontent.com/assets/14345444/9958433/b74e6058-5e01-11e5-9339-f1ad6fb0bbd3.JPG
> 
> Tim
> 
> —
> 
> Reply to this email directly or view it on GitHub 
> 
>  https://github.com/gdbaldw/BlenderAndMBDyn/issues/5.

 -- 

 Louis Gagnon, Ph.D.

 Dipartimento di Scienze e Tecnologie Aerospaziali

 Politecnico di Milano

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by louisgag** [comment]
Personally I don't, but you may find some tips on the "Cantilever" video 
posted by Doug Baldwin: 
https://www.youtube.com/user/baldwintechnology/videos
Doug is also actively coding the interface at the moment and looking for 
as much feedback as possible, so don't hesitate to request any missing 
feature!
-Louis

On 18-Sep-2015 02:46 PM, timgow wrote:

> Hi Louis,
> Thank you for your quick reply, much appreciated.
> I'm looking forward to using MBDyn within Blender, this is a fantastic 
> project.
> Enjoy your weekend too
> Tim
> 
> p.s. Do you have any experience using FEA flexible elements with MBDyn 
> and Blender?
> 
> ---
> 
> On Fri, 18/9/15, louisgag notifications@github.com wrote:
> 
> Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon 
> - No 'Actions' tab for 'Run MBDyn' (#5)
>   To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
>   Cc: "timgow" tim@gowingeng.co.uk
>   Date: Friday, 18 September, 2015, 12:49
> 
> Hi Tim,
> 
> Thanks for your question.
> 
> Unfortunately the addon is not very stable with Blender
> 2.69. The tabs
> 
> don't show clearly and the pop-ups are delayed.
> 
> I strongly recommend you download the latest Blender version
> from the
> 
> official website, on Ubuntu that download is ready to run
> out of the box
> 
> without even compiling.
> 
> Have a nice week-end,
> 
> -Louis
> 
> On 18-Sep-2015 01:35 PM, timgow wrote:
> 
> > Hi,
> > 
> > I have Blender 2.69 and MBDyn 1.6.1 installed on Ubuntu
> > 14.04 LTS. I
> > 
> > would like to use the
> > github.com/gdbaldw/BlenderAndMBDyn addon for
> > 
> > Blender. The addon goes ahead within Blender but I
> > don't get the
> > 
> > 'Actions' tab to select 'MBDyn file',
> > 'Run MBDyn' etc..
> > 
> > Please give any suggestions.
> > 
> > blendermbdyn-gdbaldw_installvideo
> > 
> > https://cloud.githubusercontent.com/assets/14345444/9958432/b749b35a-5e01-11e5-8339-7f9c2ee6057e.JPG
> > 
> > blendermbdyn-ubuntu1404lts
> > 
> > https://cloud.githubusercontent.com/assets/14345444/9958433/b74e6058-5e01-11e5-9339-f1ad6fb0bbd3.JPG
> > 
> > Tim
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/gdbaldw/BlenderAndMBDyn/issues/5.
> 
> ## 
> 
> Louis Gagnon, Ph.D.
> 
> Dipartimento di Scienze e Tecnologie Aerospaziali
> 
> Politecnico di Milano
> 
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/5#issuecomment-141441940.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by timgow** [comment]
Louis,
I have removed Blender2.69 and installed version 2.75a, but I have the same issue: No 'Actions' menu within the MBDyn tab (image attached).
I downloaded BlenderAndMBDyn-master.zip from https://github.com/gdbaldw/BlenderAndMBDyn.
Is the MBDyn executable location or working directory set within the Python script or interface within Blender?
Tim

**Comment by louisgag** [comment]
Hi again Tim,
I think you have to open the simulators pane and click "+" to create a new "initial value".
Then you can write the proper MBDyn path and once this is done you can click the "run simulation" button which appears.
Cheers,
-Louis

**Comment by gdbaldw** [comment]
Hi Tim,
Yes, the GUI has evolved and is becoming stable. The "Actions" panel was removed, and replaced with the "Simulators" panel. The more recent videos show: 1) Create an Initial value simulator in the Simulators panel, 2) Run the Initial value simulation, 3) Animate the objects. When you change your model after creating the simulator, your button labeled "Run the simulation" disappears, until you select you simulator again, at which time an updated MBDyn input file is created.
Cheers,
-Doug

**Comment by timgow** [comment]
Hi Doug,
Thank you for your mail; I was a bit slow to realise that the BAM v2 videos were BlenderAndMBDyn related and not a different topic of yours.
I am developing and scaling-up an experimental heat engine, and wish to use MBDyn to calculate bearing loads and check dynamic activity of a slender guided rod.  I am so pleased to discover your Blender project and I'm looking forward to gaining from the many advantages.  My ambitions included accounting for rod to bush clearance and the use of FEA flexible elements (component mode synthesis).
In the previous BAM interface, it was possible to import a .mov file, is this also possible in v2?  (useful for existing MBDyn simulation runs)
Can FEA flexible elements currently be included in a BAM analysis?
Can the 'tessellated surface' of an FEA mesh be used for the representation of the body within the Blender environment?

I really appreciate all of the work that has gone into developing this interface for our multi-body simulations.

Tim

---

On Fri, 18/9/15, gdbaldw notifications@github.com wrote:

 Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn' (#5)
 To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Friday, 18 September, 2015, 15:10

 Hi Tim,

 Yes, the GUI has evolved and is becoming stable. The
 "Actions" panel was removed, and replaced with the
 "Simulators" panel. The more recent videos show:
 1) Create an Initial value simulator in the Simulators
 panel, 2) Run the Initial value simulation, 3) Animate the
 objects. When you change your model after creating the
 simulator, your button labeled "Run the
 simulation" disappears, until you select you simulator
 again, at which time an updated MBDyn input file is
 created.

 Cheers,

 -Doug

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by timgow** [comment]
Louis,
Thank you for the BAM v2 video links also, the penny hadn't dropped, B-and-M Duh!
Thanks, Tim

---

On Fri, 18/9/15, louisgag notifications@github.com wrote:

 Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn' (#5)
 To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Friday, 18 September, 2015, 14:28

 Hi again Tim,

 I think you have to open the simulators pane and click
 "+" to create a new "initial value".

 Then you can write the proper MBDyn path and once this is
 done you can click the "run simulation" button
 which appears.

 Cheers,

 -Louis

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by gdbaldw** [comment]
Hi Tim,

A stand alone .mov import tool is available here: https://github.com/zanoni-mbdyn/mbdyn-blender. An Import feature may be integrated into BAM v2 later, though we've yet to make a decision on its implementation.

BAM v2 is capable of modeling and simulating all MBDyn entities. If you need an MBDyn entity that is not code yet, just let me know so that we may prioritize it.

Blender can import, for example, STL file formats. Once imported, your tessellated surface mesh may be linked to a new Blender Object, and then link the Blender Object to the motion data of an MBDyn animated node.

You are welcomed! Enjoy!

-Doug

**Comment by timgow** [comment]
Doug,
Thank you for the STL / surface mesh direction, I'll read up further.  The .mov import tool should work for me until I'm fully transferred over to BAM.
Enjoy the weekend
Tim

---

On Fri, 18/9/15, gdbaldw notifications@github.com wrote:

 Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn' (#5)
 To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Friday, 18 September, 2015, 16:34

 Hi Tim,

 A stand alone .mov import tool is available here: https://github.com/zanoni-mbdyn/mbdyn-blender.
 An Import feature may be integrated into BAM v2 later,
 though we've yet to make a decision on its
 implementation.

 BAM v2 is capable of modeling and simulating all MBDyn
 entities. If you need an MBDyn entity that is not code yet,
 just let me know so that we may prioritize it.

 Blender can import, for example, STL file formats. Once
 imported, your tessellated surface mesh may be linked to a
 new Blender Object, and then link the Blender Object to the
 motion data of an MBDyn animated node.

 You are welcomed! Enjoy!

 -Doug

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by timgow** [comment]
Doug,
I've followed the BAM_v2 rigid body tutorial, navigated my way around blender and now have an animation of the falling body from MBDyn results - that's a lot of fun.
I noticed a couple of differences between my interface and that in the video, I reckon that's down to your development of the code: 1) now there's no need to go off and create the 'Constant drive' as it's in the list when defining the structural force and 2) the Rigid offset instance has no location xyz or Euler rotation angle fields.  This second item didn't effect the current example case but I not sure about adjusting the position and attitude of the offset in a more complex case; do I use the blender 'transform' tool rather than a BAM tool?

In the post-processing stage of the tutorial, I get a problem when attempting to plot the force on the 'body', please see the attached screen shot.
ImportError: No module named 'pandas'
Is the graphing task performed by Pandas Python Data Analysis Library from http://pandas.pydata.org ?
I'm using Ubuntu 14.04 with Python showing up as version 2.7.6, do I need a particular version of Pandas, current download is release 0.17.0 ?

I appreciate your provision of this interface for our multi-body dynamic simulation.
Tim

---

On Fri, 18/9/15, gdbaldw notifications@github.com wrote:

 Subject: Re: [BlenderAndMBDyn] Blender 2.69 Ubuntu 14.04 - MBDyn addon - No 'Actions' tab for 'Run MBDyn' (#5)
 To: "gdbaldw/BlenderAndMBDyn" BlenderAndMBDyn@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Friday, 18 September, 2015, 16:34

 Hi Tim,

 A stand alone .mov import tool is available here: https://github.com/zanoni-mbdyn/mbdyn-blender.
 An Import feature may be integrated into BAM v2 later,
 though we've yet to make a decision on its
 implementation.

 BAM v2 is capable of modeling and simulating all MBDyn
 entities. If you need an MBDyn entity that is not code yet,
 just let me know so that we may prioritize it.

 Blender can import, for example, STL file formats. Once
 imported, your tessellated surface mesh may be linked to a
 new Blender Object, and then link the Blender Object to the
 motion data of an MBDyn animated node.

 You are welcomed! Enjoy!

 -Doug

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by gdbaldw** [comment]
Hi TIm,

Blender Object orientation and position may be set with the Blender interface, and for convenience it is also provided in Elements Panel, Selected Objects -> Object Specifications. This convenience function may not be in your version, but will be posted to github in a day or so.

Pandas for both Python v2 and Python v3 are required, v2 for you Linux environment and v3 for the embedded Python within Blender. I believe most any recent version of Pandas will do.

-Doug

**Comment by timgow** [comment]
Doug,
I will look out for the next BAM release wrt object position and orientation, and install Pandas for plotting results, thank you.
I am really appreciative of the existence of the BAM open-source interactive multi body dynamics simulation.  A while back I worked with loads provided by MDI/Adams for finite element stress models of engine components and later used FE flexible body data within MSC/Adams to determine crankshaft stresses inclusive of system dynamic effects.
I have ambitions of using the component mode synthesis capability within MBDyn to predict loadings within a low mass crank train; the finite element stress prediction will have to be decoupled from the MBDyn, for now.
What are your future plans for MB simulation?  Do you see CMS flexible bodies within the BAM environment? The output of MBS-FEA coupled component stresses would be fantastic, in open-source.
Tim

**Comment by gdbaldw** [comment]
Tim,
Latest is released. At the moment, this is a hobby for me, and my interest is having stable code and an active user community. The MBDyn "mode" element appears to be for CMS, so yes it may be possible. The use case is more complex than usual, with perhaps many nodes, etc., so a workflow would need to be developed, etc. I have no specific plans for this, but on a quick survey it appears doable.
-Doug
