### ISSUE TITLE
clamp appearance on screen

### ISSUE THREAD

**Issue by timgow** [gdbaldw/BlenderAndMBDyn#8]
Hi,
I'm using the latest BAM version, thank you Doug

I'm following the 'BAM v2 - rigidpendulum tutorial example' and start by making the clamp.  I create a 'cube mesh', keep it selected and 'add new element > joint > clamp.
My first concern is that the appearance doesn't change to the pointed shape seen in the video.
If I carry on following the video, I create a another 'cube mesh' for the Revolute Hinge, select the clamp, shift+select the Revolute Hinge body and 'add new element > joint > Revolute Hinge'.  This operation does change the appearance to the cylinder, as per the video.
The next operation to duplicate the Revolute Hinge does not go to plan as the move 'G Z-0.5' seems to move the whole assembly rather than just the new Revolute Hinge that is selected.
Please see images below.

Aside: It's a blender question but I don't have the ability to select the objects on the screen using the cursor, all that I get from LMB is selection of an arbitrary point in space that is then used as the position for the position of the next newly created object.  Is there a different mode for the cursor to be working in?

Tim
![screenshot from 2015-09-29 11_20_30](https://cloud.githubusercontent.com/assets/14345444/10162298/3130711a-66a2-11e5-89f9-cf5fb2ac9d9b.png)
![screenshot from 2015-09-29 11_21_31](https://cloud.githubusercontent.com/assets/14345444/10162297/312dc654-66a2-11e5-9bd1-0b1840553c96.png)
![screenshot from 2015-09-29 11_22_12](https://cloud.githubusercontent.com/assets/14345444/10162293/312968f2-66a2-11e5-8bc3-e151d4b9c5e8.png)
![screenshot from 2015-09-29 11_23_06](https://cloud.githubusercontent.com/assets/14345444/10162295/312b7368-66a2-11e5-9851-44f403f2d559.png)
![screenshot from 2015-09-29 11_25_32](https://cloud.githubusercontent.com/assets/14345444/10162294/3129ee4e-66a2-11e5-9ddc-9a82e2ca3723.png)
![screenshot from 2015-09-29 11_25_48](https://cloud.githubusercontent.com/assets/14345444/10162296/312cc358-66a2-11e5-81be-0f607b4cfd06.png)
![screenshot from 2015-09-29 11_28_31](https://cloud.githubusercontent.com/assets/14345444/10162300/3163fca6-66a2-11e5-9075-3a6339c32e6b.png)
![screenshot from 2015-09-29 11_31_13](https://cloud.githubusercontent.com/assets/14345444/10162301/316a656e-66a2-11e5-8d5c-5ba2a52d3e6e.png)
![screenshot from 2015-09-29 11_49_17](https://cloud.githubusercontent.com/assets/14345444/10162299/3144f09a-66a2-11e5-94fe-151e96510f6e.png)

**Comment by louisgag** [comment]
Hi Tim,
As we recently noticed here at Polimi, the latest BAMv2 version will 
produce those "shape" bugs you noticed on ANY Blender version other than 
Blender and not with more recent versions. I think Doug is looking into 
that.
As for selecting objects in Blender you need to use the RMB (and you can 
press "a" when hovering over the scene to select/deselect all).
I've suggested to Doug that he removes the auto-select feature when 
creating a BAM object as in my opinion it confuses the user.
I think Doug can address your other questions.
Thank for your feedback !
-Louis

On 29-Sep-2015 01:06 PM, timgow wrote:

> Hi,
> I'm using the latest BAM version, thank you Doug
> 
> I'm following the 'BAM v2 - rigidpendulum tutorial example' and start 
> by making the clamp. I create a 'cube mesh', keep it selected and 'add 
> new element > joint > clamp.
> My first concern is that the appearance doesn't change to the pointed 
> shape seen in the video.
> If I carry on following the video, I create a another 'cube mesh' for 
> the Revolute Hinge, select the clamp, shift+select the Revolute Hinge 
> body and 'add new element > joint > Revolute Hinge'. This operation 
> does change the appearance to the cylinder, as per the video.
> The next operation to duplicate the Revolute Hinge does not go to plan 
> as the move 'G Z-0.5' seems to move the whole assembly rather than 
> just the new Revolute Hinge that is selected.
> Please see images below.
> 
> Aside: It's a blender question but I don't have the ability to select 
> the objects on the screen using the cursor, all that I get from LMB is 
> selection of an arbitrary point in space that is then used as the 
> position for the position of the next newly created object. Is there a 
> different mode for the cursor to be working in?
> 
> Tim
> screenshot from 2015-09-29 11_20_30 
> https://cloud.githubusercontent.com/assets/14345444/10162298/3130711a-66a2-11e5-89f9-cf5fb2ac9d9b.png
> screenshot from 2015-09-29 11_21_31 
> https://cloud.githubusercontent.com/assets/14345444/10162297/312dc654-66a2-11e5-9bd1-0b1840553c96.png
> screenshot from 2015-09-29 11_22_12 
> https://cloud.githubusercontent.com/assets/14345444/10162293/312968f2-66a2-11e5-8bc3-e151d4b9c5e8.png
> screenshot from 2015-09-29 11_23_06 
> https://cloud.githubusercontent.com/assets/14345444/10162295/312b7368-66a2-11e5-9851-44f403f2d559.png
> screenshot from 2015-09-29 11_25_32 
> https://cloud.githubusercontent.com/assets/14345444/10162294/3129ee4e-66a2-11e5-9ddc-9a82e2ca3723.png
> screenshot from 2015-09-29 11_25_48 
> https://cloud.githubusercontent.com/assets/14345444/10162296/312cc358-66a2-11e5-81be-0f607b4cfd06.png
> screenshot from 2015-09-29 11_28_31 
> https://cloud.githubusercontent.com/assets/14345444/10162300/3163fca6-66a2-11e5-9075-3a6339c32e6b.png
> screenshot from 2015-09-29 11_31_13 
> https://cloud.githubusercontent.com/assets/14345444/10162301/316a656e-66a2-11e5-8d5c-5ba2a52d3e6e.png
> screenshot from 2015-09-29 11_49_17 
> https://cloud.githubusercontent.com/assets/14345444/10162299/3144f09a-66a2-11e5-94fe-151e96510f6e.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/8.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by timgow** [comment]
Thank you Louis,
I'll carry on with the cubic shaped clamp symbol and see if it functions ok in MBDyn.
I've now got the ctrl+RMB for selecting,
Many thanks
Tim

**Comment by gdbaldw** [comment]
Hi Tim,
With the goal of showing how fast a model can be built and simulated, I've assumed a good working knowledge of the basic Blender GUI. I'll change that assumption in a few videos to show the basics of Blender that are needed to effectively use BAM.
Behavior of everything in Blender depends on context, which changes with each selection of an Object or a group of Objects, and with the active object in a group of Objects. Selection is done with right click, ctrl-right click, and the A-Key.
As for the Clamp mesh changes you observed, if you've already selected the Cube object, you will notice that in the menu the Clamp selection does not have an orange triangle icon. This indicates that you have selected sufficient Objects for the Clamp element, and so the one you have selected will be use in the creation of the Clamp; the Cube's shape will change to a teardrop upon creation of the Clamp.
On the other hand, if you have selected no Objects, you will notice that in the menu, the Clamp selection does have the orange triangle icon. This indicates that you have one less Objects selected than what is needed for the Clamp element, and so a new Object will be created at the cursor location and this object will become the Clamp.
The behavior you observed is that you had no selections, and so the Clamp that you created was hidden by the default Cube. When you start Blender, both the default Cube and the cursor are at the origin.
By the way, when you pressed the left mouse button, you were moving the cursor within the 3D-VIEW.
I hope this all helps you for now. I'll soon have time for a few more videos to demonstrate this all.
-Doug

**Comment by timgow** [comment]
Hi Doug,
Thank you for shedding light on the item selection within Blender / BAM environment.  I'm practicing further and watching the orange triangles.
Tim

**Comment by timgow** [comment]
Hi Doug,
I have benefited greatly from your explanation of context and selection above, thank you.  In the Rigid_body example this has really helped because I had previously selected the Rigid_Offset from the LH BAM tabs, but this selects the Rigid_Offset + Body and so is incorrect for creating the force; when the Rigid_Offset is selected on-screen by toggling through ctrl+RMB, then the Rigid_offset alone is appropriate for the structural force (no orange triangle).

Clamp Appearance On-screen
I downloaded each revision of BAM over the last couple of days and have run these but I still don't see the nice clamp shape that you have in the tutorial.  I have Blender 2.75 dated 2015 07 07 so I shouldn't be behind in version.  I hope that I'm purging the python files ok.  The procedure that I use is:
1) uncheck BAM in Blender preferences and then remove BAM
2) download latest BAM zip file
3) delete old BAM zip and extracted directory
4) restart Blender and add BAM in preferences
Are the python files copied elsewhere by Blender?  Could Blender be hanging on to the old version?
Please see images below.

![screenshot from 2015-09-30 10_40_31](https://cloud.githubusercontent.com/assets/14345444/10190168/b10a9814-6762-11e5-93ac-3350a2fcc435.png)
![screenshot from 2015-09-30 10_41_23](https://cloud.githubusercontent.com/assets/14345444/10190169/b10b2914-6762-11e5-916d-a842d33fec60.png)
![screenshot from 2015-09-30 10_41_31](https://cloud.githubusercontent.com/assets/14345444/10190170/b10c9fc4-6762-11e5-8fce-a34a22bf24e9.png)

There is a behaviour for the Reference_Frame dialogue that could perhaps be enhanced (I appreciate that this workflow is already slick now with the 3x1 matrix creation being eliminated).  The 3 images below show that the when 'Set Linear rate' is selected during creation, the numerical input field is not seen until you go back to edit the frame.  I suspect that it is not straightforward to code the numerical field to appear due to the 'Set Linear rate' being ticked.

![screenshot from 2015-09-30 09_58_48](https://cloud.githubusercontent.com/assets/14345444/10190414/42d02a74-6764-11e5-81f0-12848e0941e0.png)
![screenshot from 2015-09-30 09_59_35](https://cloud.githubusercontent.com/assets/14345444/10190416/42d0cf2e-6764-11e5-9516-5cd36e705633.png)
![screenshot from 2015-09-30 09_59_49](https://cloud.githubusercontent.com/assets/14345444/10190415/42d070b0-6764-11e5-8a2f-4860039de830.png)

I'm enjoying getting familiar with the interface, the support is much appreciated.
Tim

**Comment by timgow** [comment]
Please switch 2) & 3) in the procedure above; I meant delete old then download new. Tim

**Comment by gdbaldw** [comment]
Hi Tim,
The Clamp shape bug in newer Blender releases is fixed now. As for Reference frame -> Linear rate checkbox, that works fine for me in 2.72 and 2.76. To reproduce this or any bug with diagnostics, start Blender from the Linux command line, and copy/paste any Python exceptions that are reported there.
Thanks,
Doug

**Comment by timgow** [comment]
Doug,
Thank you, nice clamp shape shows now.
Tim

**Comment by gdbaldw** [comment]
Tim,
The interface has been simplified, but not documented or updated in all the video. When you select an Element from the list, its associated Objects are selected and highlighted. To change the associated Objects, simply select the appropriate number of Objects you'd like to have associated, and then press Edit from the menu. The currently selected Objects will now be associated with the Element, and the Objects specifications will popup after you complete the edit, which is your acknowledgement that the Objects have been assigned to the Element and provides the opportunity for you to rename, reposition, and reorient.
-Doug

**Comment by louisgag** [comment]
Dear Tim and Doug,
I'm working on getting these details into the associated help manual so 
that it becomes clearer for BAMv2 users.
Please keep posting these updates !
Regards,
-Louis

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano
