### ISSUE TITLE
Can't reopen results - can't rerun analysis

### ISSUE THREAD

**Issue by timgow** [gdbaldw/BlenderAndMBDyn#9]
I successfully followed 'BAM v2 - rigidbody tutorial example', ran the MBDynanalysis and animated the results.  I then closed the blender session and reopened the blender file to check on how to revisit the analysis; unfortunately I can't review the existing results and I get an error when trying to delete the Simulations > Initial value.
Please see images below.
Is the 'Force' body in these screenshots supposed to be a child of the 'Node' body within the Blender tree?  Are the relationships within the multi-body simulation reflected in the Blender tree?

Tim

![screenshot from 2015-09-29 14_27_22](https://cloud.githubusercontent.com/assets/14345444/10167632/3d473e24-66c1-11e5-8a08-5db77b79a768.png)
![screenshot from 2015-09-29 14_27_47](https://cloud.githubusercontent.com/assets/14345444/10167631/3d42b566-66c1-11e5-8440-30f0c8b07420.png)

**Comment by gdbaldw** [comment]
Try downloading latest script from last night. I'd found the same bug and believe it is fixed.

**Comment by timgow** [comment]
Thank you Doug
